[tool.poetry]
name = "course"
version = "0.1.0"
description = ""
authors = ["Russell <ruzilkasymov5@gmail.com.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]
pytest = "^8.0.2"